# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response_default_2_func_paths import InlineResponseDefault2FuncPaths  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponseDefault2FuncPaths(unittest.TestCase):
    """InlineResponseDefault2FuncPaths unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponseDefault2FuncPaths(self):
        """Test InlineResponseDefault2FuncPaths"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_default_2_func_paths.InlineResponseDefault2FuncPaths()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
