# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response_default_1_runs import InlineResponseDefault1Runs  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponseDefault1Runs(unittest.TestCase):
    """InlineResponseDefault1Runs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponseDefault1Runs(self):
        """Test InlineResponseDefault1Runs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_default_1_runs.InlineResponseDefault1Runs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
