# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.predictors_api import PredictorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPredictorsApi(unittest.TestCase):
    """PredictorsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.predictors_api.PredictorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_predictor_events_get(self):
        """Test case for api_predictor_events_get

        Get events for predictor(s)  # noqa: E501
        """
        pass

    def test_api_predictors_get(self):
        """Test case for api_predictors_get

        Get list of predictors.  # noqa: E501
        """
        pass

    def test_api_predictors_predictor_id_get(self):
        """Test case for api_predictors_predictor_id_get

        Get predictor by id.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
