# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response_default_8 import InlineResponseDefault8  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponseDefault8(unittest.TestCase):
    """InlineResponseDefault8 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponseDefault8(self):
        """Test InlineResponseDefault8"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_default_8.InlineResponseDefault8()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
