# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApipredictorsExtractedFeature(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_at': 'str',
        'description': 'str',
        'extractor_name': 'str',
        'id': 'int',
        'modality': 'str'
    }

    attribute_map = {
        'created_at': 'created_at',
        'description': 'description',
        'extractor_name': 'extractor_name',
        'id': 'id',
        'modality': 'modality'
    }

    def __init__(self, created_at=None, description=None, extractor_name=None, id=None, modality=None):  # noqa: E501
        """ApipredictorsExtractedFeature - a model defined in Swagger"""  # noqa: E501

        self._created_at = None
        self._description = None
        self._extractor_name = None
        self._id = None
        self._modality = None
        self.discriminator = None

        if created_at is not None:
            self.created_at = created_at
        if description is not None:
            self.description = description
        if extractor_name is not None:
            self.extractor_name = extractor_name
        if id is not None:
            self.id = id
        if modality is not None:
            self.modality = modality

    @property
    def created_at(self):
        """Gets the created_at of this ApipredictorsExtractedFeature.  # noqa: E501

        Extraction timestamp.  # noqa: E501

        :return: The created_at of this ApipredictorsExtractedFeature.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ApipredictorsExtractedFeature.

        Extraction timestamp.  # noqa: E501

        :param created_at: The created_at of this ApipredictorsExtractedFeature.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def description(self):
        """Gets the description of this ApipredictorsExtractedFeature.  # noqa: E501

        Feature description.  # noqa: E501

        :return: The description of this ApipredictorsExtractedFeature.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ApipredictorsExtractedFeature.

        Feature description.  # noqa: E501

        :param description: The description of this ApipredictorsExtractedFeature.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def extractor_name(self):
        """Gets the extractor_name of this ApipredictorsExtractedFeature.  # noqa: E501

        Extractor name.  # noqa: E501

        :return: The extractor_name of this ApipredictorsExtractedFeature.  # noqa: E501
        :rtype: str
        """
        return self._extractor_name

    @extractor_name.setter
    def extractor_name(self, extractor_name):
        """Sets the extractor_name of this ApipredictorsExtractedFeature.

        Extractor name.  # noqa: E501

        :param extractor_name: The extractor_name of this ApipredictorsExtractedFeature.  # noqa: E501
        :type: str
        """

        self._extractor_name = extractor_name

    @property
    def id(self):
        """Gets the id of this ApipredictorsExtractedFeature.  # noqa: E501

        Extractor id  # noqa: E501

        :return: The id of this ApipredictorsExtractedFeature.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApipredictorsExtractedFeature.

        Extractor id  # noqa: E501

        :param id: The id of this ApipredictorsExtractedFeature.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def modality(self):
        """Gets the modality of this ApipredictorsExtractedFeature.  # noqa: E501


        :return: The modality of this ApipredictorsExtractedFeature.  # noqa: E501
        :rtype: str
        """
        return self._modality

    @modality.setter
    def modality(self, modality):
        """Sets the modality of this ApipredictorsExtractedFeature.


        :param modality: The modality of this ApipredictorsExtractedFeature.  # noqa: E501
        :type: str
        """

        self._modality = modality

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApipredictorsExtractedFeature):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
