# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.apianalyses_predictors import ApianalysesPredictors  # noqa: F401,E501


class InlineResponseDefault11(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tr': 'float',
        'dataset_id': 'int',
        'description': 'object',
        'id': 'int',
        'name': 'str',
        'num_runs': 'int',
        'runs': 'ApianalysesPredictors'
    }

    attribute_map = {
        'tr': 'TR',
        'dataset_id': 'dataset_id',
        'description': 'description',
        'id': 'id',
        'name': 'name',
        'num_runs': 'num_runs',
        'runs': 'runs'
    }

    def __init__(self, tr=None, dataset_id=None, description=None, id=None, name=None, num_runs=None, runs=None):  # noqa: E501
        """InlineResponseDefault11 - a model defined in Swagger"""  # noqa: E501

        self._tr = None
        self._dataset_id = None
        self._description = None
        self._id = None
        self._name = None
        self._num_runs = None
        self._runs = None
        self.discriminator = None

        if tr is not None:
            self.tr = tr
        if dataset_id is not None:
            self.dataset_id = dataset_id
        if description is not None:
            self.description = description
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if num_runs is not None:
            self.num_runs = num_runs
        if runs is not None:
            self.runs = runs

    @property
    def tr(self):
        """Gets the tr of this InlineResponseDefault11.  # noqa: E501


        :return: The tr of this InlineResponseDefault11.  # noqa: E501
        :rtype: float
        """
        return self._tr

    @tr.setter
    def tr(self, tr):
        """Sets the tr of this InlineResponseDefault11.


        :param tr: The tr of this InlineResponseDefault11.  # noqa: E501
        :type: float
        """

        self._tr = tr

    @property
    def dataset_id(self):
        """Gets the dataset_id of this InlineResponseDefault11.  # noqa: E501


        :return: The dataset_id of this InlineResponseDefault11.  # noqa: E501
        :rtype: int
        """
        return self._dataset_id

    @dataset_id.setter
    def dataset_id(self, dataset_id):
        """Sets the dataset_id of this InlineResponseDefault11.


        :param dataset_id: The dataset_id of this InlineResponseDefault11.  # noqa: E501
        :type: int
        """

        self._dataset_id = dataset_id

    @property
    def description(self):
        """Gets the description of this InlineResponseDefault11.  # noqa: E501

        BIDS task description  # noqa: E501

        :return: The description of this InlineResponseDefault11.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InlineResponseDefault11.

        BIDS task description  # noqa: E501

        :param description: The description of this InlineResponseDefault11.  # noqa: E501
        :type: object
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this InlineResponseDefault11.  # noqa: E501


        :return: The id of this InlineResponseDefault11.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponseDefault11.


        :param id: The id of this InlineResponseDefault11.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this InlineResponseDefault11.  # noqa: E501


        :return: The name of this InlineResponseDefault11.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponseDefault11.


        :param name: The name of this InlineResponseDefault11.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def num_runs(self):
        """Gets the num_runs of this InlineResponseDefault11.  # noqa: E501

        Number of runs.  # noqa: E501

        :return: The num_runs of this InlineResponseDefault11.  # noqa: E501
        :rtype: int
        """
        return self._num_runs

    @num_runs.setter
    def num_runs(self, num_runs):
        """Sets the num_runs of this InlineResponseDefault11.

        Number of runs.  # noqa: E501

        :param num_runs: The num_runs of this InlineResponseDefault11.  # noqa: E501
        :type: int
        """

        self._num_runs = num_runs

    @property
    def runs(self):
        """Gets the runs of this InlineResponseDefault11.  # noqa: E501


        :return: The runs of this InlineResponseDefault11.  # noqa: E501
        :rtype: ApianalysesPredictors
        """
        return self._runs

    @runs.setter
    def runs(self, runs):
        """Sets the runs of this InlineResponseDefault11.


        :param runs: The runs of this InlineResponseDefault11.  # noqa: E501
        :type: ApianalysesPredictors
        """

        self._runs = runs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponseDefault11):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
