# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponseDefault3(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'compile_traceback': 'str',
        'status': 'str'
    }

    attribute_map = {
        'compile_traceback': 'compile_traceback',
        'status': 'status'
    }

    def __init__(self, compile_traceback=None, status=None):  # noqa: E501
        """InlineResponseDefault3 - a model defined in Swagger"""  # noqa: E501

        self._compile_traceback = None
        self._status = None
        self.discriminator = None

        if compile_traceback is not None:
            self.compile_traceback = compile_traceback
        if status is not None:
            self.status = status

    @property
    def compile_traceback(self):
        """Gets the compile_traceback of this InlineResponseDefault3.  # noqa: E501

        Traceback of compilation error.  # noqa: E501

        :return: The compile_traceback of this InlineResponseDefault3.  # noqa: E501
        :rtype: str
        """
        return self._compile_traceback

    @compile_traceback.setter
    def compile_traceback(self, compile_traceback):
        """Sets the compile_traceback of this InlineResponseDefault3.

        Traceback of compilation error.  # noqa: E501

        :param compile_traceback: The compile_traceback of this InlineResponseDefault3.  # noqa: E501
        :type: str
        """

        self._compile_traceback = compile_traceback

    @property
    def status(self):
        """Gets the status of this InlineResponseDefault3.  # noqa: E501

        PASSED, FAILED, PENDING, or DRAFT.  # noqa: E501

        :return: The status of this InlineResponseDefault3.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponseDefault3.

        PASSED, FAILED, PENDING, or DRAFT.  # noqa: E501

        :param status: The status of this InlineResponseDefault3.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponseDefault3):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
