# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponseDefault1Runs(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'acquisition': 'str',
        'duration': 'float',
        'func_path': 'str',
        'id': 'int',
        'mask_path': 'str',
        'number': 'str',
        'session': 'str',
        'subject': 'str'
    }

    attribute_map = {
        'acquisition': 'acquisition',
        'duration': 'duration',
        'func_path': 'func_path',
        'id': 'id',
        'mask_path': 'mask_path',
        'number': 'number',
        'session': 'session',
        'subject': 'subject'
    }

    def __init__(self, acquisition=None, duration=None, func_path=None, id=None, mask_path=None, number=None, session=None, subject=None):  # noqa: E501
        """InlineResponseDefault1Runs - a model defined in Swagger"""  # noqa: E501

        self._acquisition = None
        self._duration = None
        self._func_path = None
        self._id = None
        self._mask_path = None
        self._number = None
        self._session = None
        self._subject = None
        self.discriminator = None

        if acquisition is not None:
            self.acquisition = acquisition
        if duration is not None:
            self.duration = duration
        if func_path is not None:
            self.func_path = func_path
        if id is not None:
            self.id = id
        if mask_path is not None:
            self.mask_path = mask_path
        if number is not None:
            self.number = number
        if session is not None:
            self.session = session
        if subject is not None:
            self.subject = subject

    @property
    def acquisition(self):
        """Gets the acquisition of this InlineResponseDefault1Runs.  # noqa: E501

        Acquisition  # noqa: E501

        :return: The acquisition of this InlineResponseDefault1Runs.  # noqa: E501
        :rtype: str
        """
        return self._acquisition

    @acquisition.setter
    def acquisition(self, acquisition):
        """Sets the acquisition of this InlineResponseDefault1Runs.

        Acquisition  # noqa: E501

        :param acquisition: The acquisition of this InlineResponseDefault1Runs.  # noqa: E501
        :type: str
        """

        self._acquisition = acquisition

    @property
    def duration(self):
        """Gets the duration of this InlineResponseDefault1Runs.  # noqa: E501

        Total run duration in seconds.  # noqa: E501

        :return: The duration of this InlineResponseDefault1Runs.  # noqa: E501
        :rtype: float
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this InlineResponseDefault1Runs.

        Total run duration in seconds.  # noqa: E501

        :param duration: The duration of this InlineResponseDefault1Runs.  # noqa: E501
        :type: float
        """

        self._duration = duration

    @property
    def func_path(self):
        """Gets the func_path of this InlineResponseDefault1Runs.  # noqa: E501

        Path of functional file  # noqa: E501

        :return: The func_path of this InlineResponseDefault1Runs.  # noqa: E501
        :rtype: str
        """
        return self._func_path

    @func_path.setter
    def func_path(self, func_path):
        """Sets the func_path of this InlineResponseDefault1Runs.

        Path of functional file  # noqa: E501

        :param func_path: The func_path of this InlineResponseDefault1Runs.  # noqa: E501
        :type: str
        """

        self._func_path = func_path

    @property
    def id(self):
        """Gets the id of this InlineResponseDefault1Runs.  # noqa: E501


        :return: The id of this InlineResponseDefault1Runs.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponseDefault1Runs.


        :param id: The id of this InlineResponseDefault1Runs.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def mask_path(self):
        """Gets the mask_path of this InlineResponseDefault1Runs.  # noqa: E501

        Path of brain mask  # noqa: E501

        :return: The mask_path of this InlineResponseDefault1Runs.  # noqa: E501
        :rtype: str
        """
        return self._mask_path

    @mask_path.setter
    def mask_path(self, mask_path):
        """Sets the mask_path of this InlineResponseDefault1Runs.

        Path of brain mask  # noqa: E501

        :param mask_path: The mask_path of this InlineResponseDefault1Runs.  # noqa: E501
        :type: str
        """

        self._mask_path = mask_path

    @property
    def number(self):
        """Gets the number of this InlineResponseDefault1Runs.  # noqa: E501

        Run id  # noqa: E501

        :return: The number of this InlineResponseDefault1Runs.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this InlineResponseDefault1Runs.

        Run id  # noqa: E501

        :param number: The number of this InlineResponseDefault1Runs.  # noqa: E501
        :type: str
        """

        self._number = number

    @property
    def session(self):
        """Gets the session of this InlineResponseDefault1Runs.  # noqa: E501

        Session number  # noqa: E501

        :return: The session of this InlineResponseDefault1Runs.  # noqa: E501
        :rtype: str
        """
        return self._session

    @session.setter
    def session(self, session):
        """Sets the session of this InlineResponseDefault1Runs.

        Session number  # noqa: E501

        :param session: The session of this InlineResponseDefault1Runs.  # noqa: E501
        :type: str
        """

        self._session = session

    @property
    def subject(self):
        """Gets the subject of this InlineResponseDefault1Runs.  # noqa: E501

        Subject id  # noqa: E501

        :return: The subject of this InlineResponseDefault1Runs.  # noqa: E501
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this InlineResponseDefault1Runs.

        Subject id  # noqa: E501

        :param subject: The subject of this InlineResponseDefault1Runs.  # noqa: E501
        :type: str
        """

        self._subject = subject

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponseDefault1Runs):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
