# coding: utf-8

"""
    neuroscout

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponseDefault2FuncPaths(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'func_path': 'str'
    }

    attribute_map = {
        'func_path': 'func_path'
    }

    def __init__(self, func_path=None):  # noqa: E501
        """InlineResponseDefault2FuncPaths - a model defined in Swagger"""  # noqa: E501

        self._func_path = None
        self.discriminator = None

        if func_path is not None:
            self.func_path = func_path

    @property
    def func_path(self):
        """Gets the func_path of this InlineResponseDefault2FuncPaths.  # noqa: E501

        Path of functional file  # noqa: E501

        :return: The func_path of this InlineResponseDefault2FuncPaths.  # noqa: E501
        :rtype: str
        """
        return self._func_path

    @func_path.setter
    def func_path(self, func_path):
        """Sets the func_path of this InlineResponseDefault2FuncPaths.

        Path of functional file  # noqa: E501

        :param func_path: The func_path of this InlineResponseDefault2FuncPaths.  # noqa: E501
        :type: str
        """

        self._func_path = func_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponseDefault2FuncPaths):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
